=== Shelzi/EPAM-XMLParser/out/production/EpamTestJava/com/epam/library/resources/bookStructure.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.example.com/library"
        xmlns:tns="http://www.example.com/library">

    <complexType name="Publication_type">
        <sequence>
            <element name="title" type="string"/>
            <element name="genre" type="tns:origintype"/>
            <element name="pages" type="positiveInteger"/>
            <element name="date" type="date"/>
            <element name="year" type="gYear"/>
            <element name="publisher" type="string"/>
            <element name="website" type="string"/>
            <element name="author" type="string"/>
        </sequence>
    </complexType>

    <simpleType name="origintype">
        <restriction base="string">
            <enumeration value="ADVENTURES"/>
            <enumeration value="DETECTIVE"/>
            <enumeration value="FOLKLORE"/>
            <enumeration value="NOVE"/>
            <enumeration value="FANTASY"/>
            <enumeration value="SCIENCE"/>
            <enumeration value="COMEDY"/>
            <enumeration value="COOKING"/>
        </restriction>
    </simpleType>

    <complexType name="booktype">
        <complexContent>
            <extension base="tns:Publication_type"/>
        </complexContent>
    </complexType>

    <complexType name="newspapertype">
        <complexContent>
            <extension base="tns:Publication_type"/>
        </complexContent>
    </complexType>


    <element name="library">
        <complexType>
            <sequence>
                <element ref="tns:Publication" maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>
	
    <element name="Publication" type="tns:Publication_type" abstract="true"/>
    <element name="book" type="tns:booktype" substitutionGroup="tns:Publication"/>
    <element name="newspaper" type="tns:newspapertype" substitutionGroup="tns:Publication"/>

</schema>

=== Shelzi/EPAM-XMLParser/src/main/resources/bookStructure.xml
<?xml version="1.0" encoding="UTF-8"?>
<library xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xmlns="http://www.example.com/library"
            xsi:schemaLocation="http://www.example.com/library  bookStructure.xsd">
   <book>
      <title>Everyday Italian</title>
      <genre>Cooking</genre>
      <author>Giada De Laurentiis</author>
      <year>2005</year>
      <pages>500</pages>
   </book>
   <book>
      <title>Makaroni</title>
      <genre>Cooking</genre>
      <author>Selzgusta de Mangusta</author>
      <year>2002</year>
      <pages>500</pages>
   </book>
   <book>
      <title>Harry Potter</title>
      <genre>Fantasy</genre>
      <author>J K. Rowling</author>
      <year>2005</year>
      <pages>500</pages>
   </book>
   <book>
      <title>Learning XML</title>
      <genre>Science</genre>
      <author>Erik T. Ray</author>
      <year>2003</year>
      <pages>500</pages>
   </book>
   <newspaper>
      <title>Вестник "Нафтан"</title>
      <publisher>Нафтан</publisher>
      <date>12-12-2012</date>
      <website>www.naftan.by</website>
      <pages>12</pages>

   </newspaper>
</library>
